### ISSUE TITLE
[Feature]: Clarify and prioritize the "Waiting for Host" message

### ISSUE THREAD

**Issue by jordihg** [Stooa/Stooa#269]
### Description of the feature

As a user I want to eliminate uncertainty and understand that I am waiting for the Host to start the fishbowl, and that there are no more actions on my part to do

### Description of the solution

On the Fishbowl "Waiting for Host" screen, users must understand that they will not be able to participate until the host allows them access. And the host has to understand that to give them access they have to select the button "Allow access to attendees"

### Behaviour
- Iterate message seats in -Seat Available- for this moment.
- Possibility of using a different view, different from the active fishbowl.
- Make fun proposals for this waiting state eg. what is a fishbowl, what can I do with the list of participants (RRSS), indicate the buttons/functionalities of the app, etc)
- Promote knowing the list of pre-fishbowl participants.

**Comment by eddsaura** [comment]
Closed with #541
