### ISSUE TITLE
[Feature]: Success page iteration when creating a scheduled fishbowl

### ISSUE THREAD

**Issue by jordihg** [Stooa/Stooa#280]
### Description of the feature

As a host, I want to clearly understand the actions I can do after I schedule a fishbowl, like share the link or edit it if I have made a mistake

### Description of the solution

On the Scheduled Fishbowl "Success page", the host must understand the actions he can do: share the scheduled fishbowl link or edit it 

### Behaviour
Clarify that the link is the same for everyone.
Reinforce that the event details has been sent to the mail with direct access to the fishbowl
Review information hierarchy. SHARING the link is the most important action at this point.
Give the option to modify the event (redirect to edit)
DESIRED: Step by step of what follows once the fishbowl is created

**Comment by eddsaura** [comment]
This has been already uploaded in pr #418
