### ISSUE TITLE
[Improvement]: reset-password is not being used

### ISSUE THREAD

**Issue by eddsaura** [Stooa/Stooa#93]
### What happened?

The page `resset-password/[token]` is not being used. Maybe we changed the way the user changes its password but we didn't delete the old way?

[Check the file](https://github.com/Stooa/Stooa/tree/main/frontend/pages/reset-password)

Can we verify? Ty

### What browsers are you seeing the problem on?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jordisala1991** [comment]
That page is used when you reset the password. We generate a mail on the backend and that mail contains a link with a token to that page. AFAIK there is no other way to reset the password of a user.

**Comment by eddsaura** [comment]
> That page is used when you reset the password. We generate a mail on the backend and that mail contains a link with a token to that page. AFAIK there is no other way to reset the password of a user.

Thanks jordi, I was locking my search at frontend/ folder. Closing issue!
